### ISSUE TITLE
Index OER from DuePublico

### ISSUE THREAD

**Issue by acka47** [hbz/oerindex#1]
See service description at https://duepublico2.uni-due.de//content/oer/oer-visitenkarte.json

**Comment by acka47** [comment]
DuePublico has an OAI-PMH interface so we have three different test source together: HTML, embedded JSON & XML via OAI-PMH.

**Comment by fsteeg** [comment]
We discussed offline that we want to try using the Metafacture `OaiPmhOpener` from our old metafacture-core fork in https://github.com/hbz/metafacture-core/blob/4.0.0-HBZ-SNAPSHOT/src/main/java/org/culturegraph/mf/stream/source/OaiPmhOpener.java with the current Metafacture for this. If it works out, we'd like to merge the `OaiPmhOpener` into the current metafacture-core (in `metafacture-io` or `metafacture-biblio`). Usage in Flux would look something like:

`"https://duepublico2.uni-due.de/servlets/OAIDataProvider" | open-oaipmh(metadataPrefix="mods", setSpec="collection:OER") | decode-...`

**Comment by acka47** [comment]
Moved to https://gitlab.com/oersi/oersi-etl/-/issues/1. Closing.
